var colors = require('colors');

var data = [
	'翟士丹 (mail@stanzhai.site)'.bgGreen.black,
	'',
	'自我介绍'.green.bold,
	'6年+工作经验，现居北京',
	'专注大数据，Apache Spark Contributor，了解大数据生态常用开源系统，有丰富的大数据BI系统构建经验；',
	'熟悉SQL、Web技术栈及Linux；工具控；热爱编码，喜欢探索未知领域。',
	'',
	'教育经历'.green.bold,
	'曲阜师范大学 软件工程，2008-2012，本科',
	'',
	'职业相关'.green.bold,
	'方向：'.bold + '大数据平台、分布式存储/计算；后端开发；',
	'技术栈：'.bold + 'Spark、Hive、Hadoop、Nodejs、Docker、OpenResty',
	'编程语言：'.bold + 'Scala、Python、Go ...',
	'编辑器：'.bold + 'Vim',
	'',
	'工作经历'.green.bold,
	'海致：'.bold + '架构师，2014.12，SaaS BI(BDP)大数据平台负责人，核心研发',
	'搜狐·畅游：'.bold + '研发组长，2012.07，游戏数据分析平台；爬虫、舆情分析系统；信息安全审计系统',
	'浪潮：'.bold + '实习，2011.12，空军装备研究院，作战指挥系统（C++）',
	'',
	'项目经验'.green.bold,
	'BDP商业数据分析平台'.bold + ' Spark, BI 2014-至今 ' + 'https://www.bdp.cn'.blue,
	'- 基于Spark实现通用查询及建模服务，为BDP提供基础计算能力',
	'- Spark性能优化及Bug修复（Spark 0.9 -> 2.3)',
	'- 实现Spark任务过载保护及自愈机制',
	'- 实现多级查询缓存模块',
	'- 实现支持Update、Delete的数据接入服务',
	'- 基于分区表实现物化视图执行机制，改进超大表建模速度',
	'- 基于Go实现基于优先级及Quota机制的查询调度模块',
	'- 参与实现并行DAG数据建模任务调度系统',
	'- 基于Node.js实现运维管理平台，用于BDP服务监控及问题排查',
	'- WIP: 基于Structured Streaming实现通用流式计算平台',
	'',
	'其他'.green.bold,
	'GitHub：'.bold + 'https://github.com/stanzhai'.blue,
	'专栏：'.bold + 'https://zhuanlan.zhihu.com/bigdata-spark'.blue,
	'Blog: '.bold + 'https://stanzhai.site'.blue,
	'折腾: '.bold + 'https://www.zhihu.com/question/51314788/answer/144324074'.blue
];

console.log(data.join('\n'));
